/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mytechapp.gui;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mytechapp.dao.ExamDao;
import mytechapp.dao.PerformanceDao;
import mytechapp.dao.QuestionDao;
import mytechapp.pojo.AnswerPojo;
import mytechapp.pojo.AnswerStore;
import mytechapp.pojo.ExamPojo;
import mytechapp.pojo.PerformancePojo;
import mytechapp.pojo.QuestionPojo;
import mytechapp.pojo.QuestionStore;
import mytechapp.pojo.UserProfile;

/**
 *
 * @author HP
 */
public class TakeTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form TakeTest
     */ private ExamPojo exam;
    private QuestionStore qstore;
    private AnswerStore answerstore;
    private int qno,pos=0;
    
    public TakeTestFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbUser.setText("Hello "+UserProfile.getUsername());
        qstore=new QuestionStore();
        answerstore=new AnswerStore();
        qno=1;
        lbQueNo.setText(lbQueNo.getText()+" "+qno);
    }
    public TakeTestFrame(ExamPojo exam){
    this();
    this.exam=exam;
    lb.setText(exam.getLanguage().toUpperCase() +" Paper");
    loadQuestion();
    showQuestion();
    
    }
    
    
    
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbUser = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbQueNo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taQuestion = new javax.swing.JTextArea();
        rbOption1 = new javax.swing.JRadioButton();
        rbOption2 = new javax.swing.JRadioButton();
        rbOption3 = new javax.swing.JRadioButton();
        rbOption4 = new javax.swing.JRadioButton();
        btNext = new javax.swing.JButton();
        btDone = new javax.swing.JButton();
        btCancle = new javax.swing.JButton();
        btPrevious = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbUser.setBackground(new java.awt.Color(0, 0, 0));
        lbUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUser.setForeground(new java.awt.Color(255, 102, 0));

        lb.setBackground(new java.awt.Color(0, 0, 0));
        lb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb.setForeground(new java.awt.Color(204, 51, 0));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 102, 0));
        lblLogout.setText("LOGOUT");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\java project batch\\TECH-QUIZ-APP\\TECH QUIZ APP\\onlineexam\\good luck2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        lbQueNo.setBackground(new java.awt.Color(0, 0, 0));
        lbQueNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbQueNo.setForeground(new java.awt.Color(255, 102, 0));

        taQuestion.setColumns(20);
        taQuestion.setRows(5);
        jScrollPane1.setViewportView(taQuestion);

        rbOption1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbOption1);
        rbOption1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbOption1.setForeground(new java.awt.Color(255, 102, 0));
        rbOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOption1ActionPerformed(evt);
            }
        });

        rbOption2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbOption2);
        rbOption2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbOption2.setForeground(new java.awt.Color(255, 102, 0));
        rbOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOption2ActionPerformed(evt);
            }
        });

        rbOption3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbOption3);
        rbOption3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbOption3.setForeground(new java.awt.Color(255, 102, 0));
        rbOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOption3ActionPerformed(evt);
            }
        });

        rbOption4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbOption4);
        rbOption4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbOption4.setForeground(new java.awt.Color(255, 102, 0));
        rbOption4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOption4ActionPerformed(evt);
            }
        });

        btNext.setBackground(new java.awt.Color(0, 0, 0));
        btNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNext.setForeground(new java.awt.Color(255, 51, 0));
        btNext.setText("Next");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });

        btDone.setBackground(new java.awt.Color(0, 0, 0));
        btDone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btDone.setForeground(new java.awt.Color(255, 51, 0));
        btDone.setText("Done");
        btDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoneActionPerformed(evt);
            }
        });

        btCancle.setBackground(new java.awt.Color(0, 0, 0));
        btCancle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btCancle.setForeground(new java.awt.Color(255, 51, 0));
        btCancle.setText("Cancel");
        btCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancleActionPerformed(evt);
            }
        });

        btPrevious.setBackground(new java.awt.Color(0, 0, 0));
        btPrevious.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btPrevious.setForeground(new java.awt.Color(255, 51, 0));
        btPrevious.setText("Previous");
        btPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbQueNo, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(btNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(rbOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rbOption2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCancle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(rbOption4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addComponent(btDone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQueNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOption1)
                    .addComponent(rbOption2))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOption3)
                    .addComponent(rbOption4))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDone, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(btNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCancle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        this.dispose();
        LoginFrame lf=new LoginFrame();
        lf.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setForeground(Color.white);
        Font f=new Font("Tahoma",Font.ITALIC,12);
        lblLogout.setFont(f);// TODO add your handling code here:
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setForeground(new Color(255,153,0));
        Font f=new Font("Tahoma",Font.BOLD,12);
        lblLogout.setFont(f);    // TODO add your handling code here:
    }//GEN-LAST:event_lblLogoutMouseExited

    private void rbOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOption1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOption1ActionPerformed

    private void rbOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOption2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOption2ActionPerformed

    private void rbOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOption3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOption3ActionPerformed

    private void rbOption4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOption4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOption4ActionPerformed

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
String chosenAnswer=getUserAnswer();
        if(chosenAnswer!=null){
        QuestionPojo question=qstore.getQuestion(pos);
        String correctAnswer=question.getCorrectAnswer();
        AnswerPojo newanswer=new AnswerPojo(exam.getExamId(),exam.getLanguage(),qno,chosenAnswer,correctAnswer);
            System.out.println(newanswer);
        AnswerPojo answer=answerstore.getAnswerByQno(qno);
        if(answer==null)
            answerstore.setAnswerAt(pos,newanswer);
        else{
            if(newanswer.getChosenanswer().equals(answer.getChosenanswer())==false)
            {    int apos=answerstore.removeAnswer(pos);
                 answerstore.setAnswerAt(apos,newanswer);
            }    
        
        }
        
        }
        pos++;
        if(pos>=qstore.getCount())
            pos=0;
        qno++;
        if(qno>qstore.getCount())
            qno=1;
        lbQueNo.setText("Question no: "+qno);
        showQuestion();    
        
    }//GEN-LAST:event_btNextActionPerformed

    private void btDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoneActionPerformed
       String chosenAnswer=getUserAnswer();
        if(chosenAnswer!=null){
        QuestionPojo question=qstore.getQuestion(pos);
        String correctAnswer=question.getCorrectAnswer();
        AnswerPojo newanswer=new AnswerPojo(exam.getExamId(),exam.getLanguage(),qno,chosenAnswer,correctAnswer);
            System.out.println(newanswer);
        AnswerPojo answer=answerstore.getAnswerByQno(qno);
        if(answer==null)
            answerstore.addAnswer(newanswer);
        else{
            if(newanswer.getChosenanswer().equals(answer.getChosenanswer())==false)
            {    int apos=answerstore.removeAnswer(pos);
                 answerstore.setAnswerAt(apos,newanswer);
            }    
        
        }
        
        }
        int right=0,wrong=0;
        for(QuestionPojo question:qstore.getAllQuestions()){
            int qno=question.getQno();
            AnswerPojo answer=answerstore.getAnswer(qno-1);
            if(answer==null)
                continue;
            else{
                String chosenanswer1=answer.getChosenanswer();
                String correctanswer=answer.getCorrectanswer();
                if(chosenanswer1.equals(correctanswer))
                    ++right;
                else
                    ++wrong;
            }
        }
        String report="Total Questions: "+qstore.getCount();
        report+="\nRight Answers: "+right;
        report+="\nWrong Answers: "+wrong;
        report+="\nUnAtttempted: "+(qstore.getCount()-(right+wrong));
        JOptionPane.showMessageDialog(null,report,"Your result!",JOptionPane.INFORMATION_MESSAGE);
        try{
        PerformancePojo performance=new PerformancePojo(exam.getExamId(),exam.getLanguage(),UserProfile.getUsername(),right,wrong,qstore.getCount()-(right+wrong),(double)right/qstore.getCount()*100);
        PerformanceDao.addPerformance(performance);
        JOptionPane.showMessageDialog(null,"Your Performance has been successfully added to the database","Performance added!",JOptionPane.INFORMATION_MESSAGE);
        ChoosePaperFrame cpf=new ChoosePaperFrame();
        cpf.setVisible(true);
        this.dispose();
        } 
        catch (SQLException ex) {
          JOptionPane.showMessageDialog(null,"Error while connecting to DB!","Error!!",JOptionPane.ERROR_MESSAGE);
         
        
        }
        
    }//GEN-LAST:event_btDoneActionPerformed

    private void btCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancleActionPerformed
        ChoosePaperFrame cpf=new ChoosePaperFrame();
        cpf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancleActionPerformed

    private void btPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreviousActionPerformed
        String chosenAnswer=getUserAnswer();
        if(chosenAnswer!=null){
        QuestionPojo question=qstore.getQuestion(pos);
        String correctAnswer=question.getCorrectAnswer();
        AnswerPojo newanswer=new AnswerPojo(exam.getExamId(),exam.getLanguage(),qno,chosenAnswer,correctAnswer);
            System.out.println(newanswer);
        AnswerPojo answer=answerstore.getAnswerByQno(qno);
        if(answer==null)
            answerstore.addAnswer(newanswer);
        else{
            if(newanswer.getChosenanswer().equals(answer.getChosenanswer())==false)
            {    int apos=answerstore.removeAnswer(pos);
                 answerstore.setAnswerAt(apos,newanswer);
            }    
        
        }
        
        }
        pos--;
        if(pos<0)
            pos=qstore.getCount()-1;
        qno--;
        if(qno<1)
            qno=qstore.getCount();
        lbQueNo.setText("Question no: "+qno);
        showQuestion(); 
    }//GEN-LAST:event_btPreviousActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancle;
    private javax.swing.JButton btDone;
    private javax.swing.JButton btNext;
    private javax.swing.JButton btPrevious;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lbQueNo;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JRadioButton rbOption1;
    private javax.swing.JRadioButton rbOption2;
    private javax.swing.JRadioButton rbOption3;
    private javax.swing.JRadioButton rbOption4;
    private javax.swing.JTextArea taQuestion;
    // End of variables declaration//GEN-END:variables

private void loadQuestion(){
try{
ArrayList<QuestionPojo> questionlist=QuestionDao.getQuestionByExamId(exam.getExamId());
for(QuestionPojo q:questionlist){
qstore.addQuestion(q);
}
}
catch(SQLException ex){
JOptionPane.showMessageDialog(null,"Error while Connecting DB!","Error!!",JOptionPane.ERROR_MESSAGE);    
ex.printStackTrace();
}

}
private void showQuestion(){
    QuestionPojo question=qstore.getQuestion(pos);
    buttonGroup1.clearSelection();
    taQuestion.setText(question.getQuestion());
    rbOption1.setText(question.getAnswer1());
    rbOption3.setText(question.getAnswer3());
    rbOption2.setText(question.getAnswer2());
    rbOption4.setText(question.getAnswer4());
    AnswerPojo answer=answerstore.getAnswerByQno(qno);
    if(answer==null)
        return;
    String chosenAnswer=answer.getChosenanswer();
    switch(chosenAnswer){
        case "Answer1":
                rbOption1.setSelected(true);
                break;
        case "Answer2":
                rbOption2.setSelected(true);
                break;
        case "Answer3":
                rbOption3.setSelected(true);
                break;
        case "Answer4":
                rbOption4.setSelected(true);
                break;        
    }
    
}

public String getUserAnswer(){
    if(rbOption1.isSelected())
        return "Answer1";
    else if(rbOption2.isSelected())
        return "Answer2";
    else if(rbOption3.isSelected())
        return "Answer3";
    else if(rbOption4.isSelected())
        return "Answer4";
    else
        return null;
}
}
